Repository AY2425S2-CS2103T-T12-2/tp, pull requests merged in 2025-03, with the labels that each got.

#39 Update _config.yml, _base.scss to reflect Project Title
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task

#40 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#47 Fix Add Command to enable role field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#58 Add patient and staff command
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Story, priority.High

#62 Update User Interface
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, priority.Medium

#66 Fix testcases for successful build
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/ResultDisplay.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Task, priority.Medium

#69 Update Documentation and UI Images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findSarahPeterResult.png
  docs/index.md
Labels: type.Task, priority.High

#77 Add test coverage for AddPatientCommand and AddStaffCommand
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
Labels: type.Task, priority.Medium

#80 Update Userguide and others for release
  build.gradle
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#81 Add test coverage
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
Labels: type.Task, priority.Medium

#94 Edit UserGuide addpatient command param prefix
  docs/UserGuide.md
Labels: type.Task, priority.Medium, severity.VeryLow

#92 Improve Ui
  build.gradle
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StaffListCard.fxml
Labels: type.Task, priority.Medium, severity.Low

#108 Quick Fix on Ui
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task

#109 Update model UML
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task, severity.Medium
