Repository AY2425S2-CS2103T-T12-2/tp, pull requests merged in 2025-04, with the labels that each got.

#150 Refine help command based on alpha-test bug report
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement

#151 Refine edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Task

#154 Refinement: Ui, Add Commands, Change of Guardian to Nok, Removal of Tag
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DepartmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/HealthcareStaff.java
  src/main/java/seedu/address/model/person/NextOfKin.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ProviderRole.java
  src/main/java/seedu/address/model/person/ProviderRoleContainsKeywordPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/StaffListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalStaff.java
Labels: type.Enhancement, type.Task, priority.High, severity.High, alpha-bug

#164 Add CLI Command to toggle between Dark and Light Mode
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ToggleThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ToggleThemeCommandTest.java
Labels: type.Enhancement, priority.Medium

#166 Allow phone number and email to take in the value NA if not available
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Enhancement, type.Task, priority.Medium, severity.Medium

#173 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Low, severity.Medium

#179 Update Content Panel CSS
  docs/images/SuccessfulAddPatient.png
  docs/images/SuccessfulAddStaff.png
  docs/images/SuccessfulEdit.png
  docs/images/Ui.png
  docs/images/findAlexCharlotteResult.png
  docs/images/helpWindow.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/ContentPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, priority.Medium

#255 Bug Fix: UI Truncation, Message Display
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/ui/ContentPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ContentPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug, priority.High, severity.High

#260 Bug Fix: Issue with "Selected" Person being "Unselected" on edits
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: type.Bug, severity.Medium

#254 bug fixes for PE-D
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/StaffListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalStaff.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#261 Bug Fix: Clear ContentPanel if "Selected" person is "Deleted"
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/model/person/HealthcareStaff.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/parser/AddPatientCommandParserTest.java
Labels: type.Bug, severity.High

#266 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.High, severity.High, alpha-bug

#267 Refactor Extensions.css to Styles.css
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/Styles.css
Labels: priority.Medium

#269 Update UML Diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/helpWindow.png
  src/main/resources/images/caringbook.png
Labels: type.Task, priority.High

#277 Update Documentation
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/images/delete3.png
Labels: type.Task, priority.High
